name: cd
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/plugin-cd.yml@main
    secrets: inherit
